In [1]:
import pandas as pd
import numpy as np

In [2]:
climate_df = pd.read_csv('datasets/weather/Kenya_All_Counties_Climate_Data_2010_2024.csv')
soil_df = pd.read_csv('datasets/soil/Kenya_Counties_Soil_pH.csv')

In [3]:
# clean county names
climate_df["County"] = climate_df["County"].str.strip().str.lower()
soil_df["County"] = soil_df["County"].str.strip().str.lower()

In [4]:
soil_df

             County  Latitude  Longitude  Soil_pH_0_5cm
0           mombasa   -4.0435    39.6682            NaN
1             kwale   -4.1737    39.4521            5.8
2            kilifi   -3.5106    39.9093            6.3
3        tana river   -1.5011    40.0334            7.4
4              lamu   -2.2697    40.9020            NaN
5      taita taveta   -3.3980    38.5560            6.7
6           garissa   -0.4532    39.6460            NaN
7             wajir    1.7471    40.0573            7.6
8           mandera    3.9373    41.8569            NaN
9          marsabit    2.3284    37.9899            7.0
10           isiolo    0.3556    37.5822            6.5
11             meru    0.0470    37.6498            5.5
12    tharaka-nithi   -0.2965    37.7237            5.9
13             embu   -0.5394    37.4572            5.9
14            kitui   -1.3670    38.0106            6.4
15         machakos   -1.5177    37.2634            6.1
16          makueni   -1.8041    37.6200            6.0
17        nyandarua   -0.1800    36.5220            5.8
18            nyeri   -0.4167    36.9500            6.2
19        kirinyaga   -0.6591    37.3827            5.9
20         murang'a   -0.7167    37.1500            6.0
21           kiambu   -1.1714    36.8356            6.1
22          turkana    3.1167    35.6000            7.9
23       west pokot    1.6210    35.2300            6.2
24          samburu    1.2150    36.9540            7.0
25      trans nzoia    1.0191    35.0023            NaN
26      uasin gishu    0.5143    35.2698            6.1
27  elgeyo-marakwet    0.8025    35.4780            5.9
28            nandi    0.1836    35.1260            5.6
29          baringo    0.4667    35.9667            6.8
30         laikipia    0.3600    36.7819            6.9
31           nakuru   -0.3031    36.0800            NaN
32            narok   -1.0870    35.8640            6.7
33          kajiado   -1.8523    36.7768            6.7
34          kericho   -0.3670    35.2830            NaN
35            bomet   -0.7830    35.3420            NaN
36         kakamega    0.2827    34.7519            NaN
37           vihiga    0.0780    34.7210            5.5
38          bungoma    0.5690    34.5580            NaN
39            busia    0.4600    34.1110            NaN
40            siaya    0.0610    34.2880            5.6
41           kisumu   -0.1022    34.7617            NaN
42         homa bay   -0.5273    34.4571            NaN
43           migori   -1.0634    34.4731            NaN
44            kisii   -0.6833    34.7667            5.4
45          nyamira   -0.5667    34.9333            5.3
46          nairobi   -1.2864    36.8172            NaN

In [5]:
# filling null value for mombasa by using near couties mean
# Define neighbors
mombasa_neighbors = ["kwale", "kilifi", "taita taveta"]

# Calculate average soil pH
mombasa_avg_ph = soil_df[
    soil_df["County"].isin(mombasa_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Mombasa soil pH:", mombasa_avg_ph)

# filling null values for nairobi
nairobi_neighbors = ["kiambu", "machakos", "kajiado", "murang'a"]

nairobi_avg_ph = soil_df[
    soil_df["County"].isin(nairobi_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Nairobi soil pH:", nairobi_avg_ph)

# filling null values for garissa
garissa_neighbors = ["wajir", "marsabit"]

garissa_avg_ph = soil_df[
    soil_df["County"].isin(garissa_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Garissa soil pH:", garissa_avg_ph)

# filling null values for trans nzoia
trans_neighbors = ["turkana", "west pokot", "samburu", "uasin gishu"]

trans_avg_ph = soil_df[
    soil_df["County"].isin(trans_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Trans Nzoia soil pH:", trans_avg_ph)

# filling null values for nakuru
nakuru_neighbors = ["laikipia", "narok", "kajiado"]

nakuru_avg_ph = soil_df[
    soil_df["County"].isin(nakuru_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Nakuru soil pH:", nakuru_avg_ph)

# filling null values for nakuru
kakamega_neighbors = ["vihiga", "siaya", "kisii", "nyamira"]

kakamega_avg_ph = soil_df[
    soil_df["County"].isin(kakamega_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Kakamega soil pH:", kakamega_avg_ph)

Estimated Mombasa soil pH: 6.266666666666667
Estimated Nairobi soil pH: 6.225
Estimated Garissa soil pH: 7.3
Estimated Trans Nzoia soil pH: 6.800000000000001
Estimated Nakuru soil pH: 6.766666666666667
Estimated Kakamega soil pH: 5.45

In [6]:
# filling the missing values
# Fill Mombasa
soil_df.loc[
    (soil_df["County"] == "mombasa") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = mombasa_avg_ph

# fill for lamu use for momabase bcz they are on the same region
soil_df.loc[
    (soil_df["County"] == "lamu") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = mombasa_avg_ph

# Fill Nairobi
soil_df.loc[
    (soil_df["County"] == "nairobi") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nairobi_avg_ph


# Fill Garissa
soil_df.loc[
    (soil_df["County"] == "garissa") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = garissa_avg_ph

# Fill Mandera use Garissa because they are on the same region
soil_df.loc[
    (soil_df["County"] == "mandera") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = garissa_avg_ph

# Fill Trans Nzoia
soil_df.loc[
    (soil_df["County"] == "trans nzoia") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = trans_avg_ph

# Fill Nakuru
soil_df.loc[
    (soil_df["County"] == "nakuru") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nakuru_avg_ph

# Fill Kericho - use nakuru
soil_df.loc[
    (soil_df["County"] == "kericho") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nakuru_avg_ph

# Fill bomet - use nakuru
soil_df.loc[
    (soil_df["County"] == "bomet") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nakuru_avg_ph

# Fill kakamega
soil_df.loc[
    (soil_df["County"] == "kakamega") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill bungoma
soil_df.loc[
    (soil_df["County"] == "bungoma") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill busia - use kakamega
soil_df.loc[
    (soil_df["County"] == "busia") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill kisumu - use kakamega
soil_df.loc[
    (soil_df["County"] == "kisumu") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill homa bay - use kakamega
soil_df.loc[
    (soil_df["County"] == "homa bay") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill migori - use kakamega
soil_df.loc[
    (soil_df["County"] == "migori") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

In [7]:
soil_df

             County  Latitude  Longitude  Soil_pH_0_5cm
0           mombasa   -4.0435    39.6682       6.266667
1             kwale   -4.1737    39.4521       5.800000
2            kilifi   -3.5106    39.9093       6.300000
3        tana river   -1.5011    40.0334       7.400000
4              lamu   -2.2697    40.9020       6.266667
5      taita taveta   -3.3980    38.5560       6.700000
6           garissa   -0.4532    39.6460       7.300000
7             wajir    1.7471    40.0573       7.600000
8           mandera    3.9373    41.8569       7.300000
9          marsabit    2.3284    37.9899       7.000000
10           isiolo    0.3556    37.5822       6.500000
11             meru    0.0470    37.6498       5.500000
12    tharaka-nithi   -0.2965    37.7237       5.900000
13             embu   -0.5394    37.4572       5.900000
14            kitui   -1.3670    38.0106       6.400000
15         machakos   -1.5177    37.2634       6.100000
16          makueni   -1.8041    37.6200       6.000000
17        nyandarua   -0.1800    36.5220       5.800000
18            nyeri   -0.4167    36.9500       6.200000
19        kirinyaga   -0.6591    37.3827       5.900000
20         murang'a   -0.7167    37.1500       6.000000
21           kiambu   -1.1714    36.8356       6.100000
22          turkana    3.1167    35.6000       7.900000
23       west pokot    1.6210    35.2300       6.200000
24          samburu    1.2150    36.9540       7.000000
25      trans nzoia    1.0191    35.0023       6.800000
26      uasin gishu    0.5143    35.2698       6.100000
27  elgeyo-marakwet    0.8025    35.4780       5.900000
28            nandi    0.1836    35.1260       5.600000
29          baringo    0.4667    35.9667       6.800000
30         laikipia    0.3600    36.7819       6.900000
31           nakuru   -0.3031    36.0800       6.766667
32            narok   -1.0870    35.8640       6.700000
33          kajiado   -1.8523    36.7768       6.700000
34          kericho   -0.3670    35.2830       6.766667
35            bomet   -0.7830    35.3420       6.766667
36         kakamega    0.2827    34.7519       5.450000
37           vihiga    0.0780    34.7210       5.500000
38          bungoma    0.5690    34.5580       5.450000
39            busia    0.4600    34.1110       5.450000
40            siaya    0.0610    34.2880       5.600000
41           kisumu   -0.1022    34.7617       5.450000
42         homa bay   -0.5273    34.4571       5.450000
43           migori   -1.0634    34.4731       5.450000
44            kisii   -0.6833    34.7667       5.400000
45          nyamira   -0.5667    34.9333       5.300000
46          nairobi   -1.2864    36.8172       6.225000

In [8]:
climate_df.head()

         Date  T2M_MAX  T2M_MIN  PRECTOTCORR   RH2M   County
0  2010-01-01    34.38    23.11         0.45  71.63  mombasa
1  2010-01-02    34.48    23.29         2.17  72.44  mombasa
2  2010-01-03    32.05    23.79         1.89  75.17  mombasa
3  2010-01-04    34.33    23.96         0.39  70.45  mombasa
4  2010-01-05    35.09    23.48         1.44  70.43  mombasa

In [9]:
# merge datasets
merged_df = pd.merge(
    climate_df,
    soil_df,
    on="County",
    how="left"
)

In [10]:
merged_df

,Date,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,County,Latitude,Longitude,Soil_pH_0_5cm
0,2010-01-01,34.38,23.11,0.45,71.63,mombasa,-4.0435,39.6682,6.266667
1,2010-01-02,34.48,23.29,2.17,72.44,mombasa,-4.0435,39.6682,6.266667
2,2010-01-03,32.05,23.79,1.89,75.17,mombasa,-4.0435,39.6682,6.266667
3,2010-01-04,34.33,23.96,0.39,70.45,mombasa,-4.0435,39.6682,6.266667
4,2010-01-05,35.09,23.48,1.44,70.43,mombasa,-4.0435,39.6682,6.266667
...,...,...,...,...,...,...,...,...,...
257508,2024-12-27,27.77,14.79,0.14,69.84,nairobi,-1.2864,36.8172,6.225000
257509,2024-12-28,27.24,14.91,0.07,68.94,nairobi,-1.2864,36.8172,6.225000
257510,2024-12-29,28.55,13.60,0.01,64.06,nairobi,-1.2864,36.8172,6.225000
257511,2024-12-30,28.04,13.93,0.05,65.32,nairobi,-1.2864,36.8172,6.225000
257512,2024-12-31,28.35,14.07,0.10,67.79,nairobi,-1.2864,36.8172,6.225000

In [12]:
merged_df.describe()

,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,Latitude,Longitude,Soil_pH_0_5cm
count,257513.000000,257513.000000,257513.000000,257513.000000,257513.000000,257513.000000,257513.000000
mean,27.828646,16.917751,3.432169,69.586028,-0.371811,36.800251,6.252305
std,4.289686,4.146640,6.795233,11.984808,1.593042,1.939822,0.656382
min,15.020000,3.710000,0.000000,15.470000,-4.173700,34.111000,5.300000
25%,24.710000,14.030000,0.160000,62.080000,-1.171400,35.126000,5.600000
50%,27.470000,16.090000,1.010000,71.660000,-0.367000,36.781900,6.200000
75%,30.520000,19.480000,3.740000,78.640000,0.460000,37.723700,6.766667
max,41.890000,30.670000,408.400000,94.950000,3.937300,41.856900,7.900000

In [13]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 257513 entries, 0 to 257512
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           257513 non-null  str
 1   T2M_MAX        257513 non-null  float64
 2   T2M_MIN        257513 non-null  float64
 3   PRECTOTCORR    257513 non-null  float64
 4   RH2M           257513 non-null  float64
 5   County         257513 non-null  str
 6   Latitude       257513 non-null  float64
 7   Longitude      257513 non-null  float64
 8   Soil_pH_0_5cm  257513 non-null  float64
dtypes: float64(7), str(2)
memory usage: 17.7 MB

In [14]:
merged_df

,Date,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,County,Latitude,Longitude,Soil_pH_0_5cm
0,2010-01-01,34.38,23.11,0.45,71.63,mombasa,-4.0435,39.6682,6.266667
1,2010-01-02,34.48,23.29,2.17,72.44,mombasa,-4.0435,39.6682,6.266667
2,2010-01-03,32.05,23.79,1.89,75.17,mombasa,-4.0435,39.6682,6.266667
3,2010-01-04,34.33,23.96,0.39,70.45,mombasa,-4.0435,39.6682,6.266667
4,2010-01-05,35.09,23.48,1.44,70.43,mombasa,-4.0435,39.6682,6.266667
...,...,...,...,...,...,...,...,...,...
257508,2024-12-27,27.77,14.79,0.14,69.84,nairobi,-1.2864,36.8172,6.225000
257509,2024-12-28,27.24,14.91,0.07,68.94,nairobi,-1.2864,36.8172,6.225000
257510,2024-12-29,28.55,13.60,0.01,64.06,nairobi,-1.2864,36.8172,6.225000
257511,2024-12-30,28.04,13.93,0.05,65.32,nairobi,-1.2864,36.8172,6.225000
257512,2024-12-31,28.35,14.07,0.10,67.79,nairobi,-1.2864,36.8172,6.225000

In [15]:
# print null soil PH
null_soil = merged_df[merged_df["Soil_pH_0_5cm"].isnull()]
print(null_soil)

Empty DataFrame
Columns: [Date, T2M_MAX, T2M_MIN, PRECTOTCORR, RH2M, County, Latitude, Longitude, Soil_pH_0_5cm]
Index: []

In [16]:
# crop requirements dataset
crop_requirements_df = pd.read_csv('datasets/crop_requirements/crop_requirements.csv')
crop_requirements_df

                  Crop  Min_Temp  Max_Temp  Min_Rain  Max_Rain  Min_pH  Max_pH
0                Maize        18        30       500       800     5.5     7.5
1                Beans        16        28       400       700     6.0     7.5
2                 Rice        20        35      1000      2000     5.0     6.5
3                Wheat        10        25       500      1200     6.0     7.5
4              Sorghum        20        35       300       800     5.0     7.5
5         Irish Potato        15        22       600      1200     5.0     6.5
6               Tomato        18        30       600      1200     5.5     7.5
7                Onion        13        24       500      1000     6.0     7.5
8   Kale (Sukuma Wiki)        16        28       500      1000     5.5     7.5
9               Coffee        15        24      1200      2000     6.0     6.5
10                 Tea        10        20      1200      2500     4.5     5.5

In [17]:
# get market prices for crops data
maize_market_prices_df = pd.read_csv('datasets/crop_prices/csv/maize_market_prices.csv')
maize_market_prices_df = maize_market_prices_df[["Commodity", "Wholesale", "Retail", "County", "Date"]]
# remove /kg
maize_market_prices_df["Wholesale"] = maize_market_prices_df["Wholesale"].str.replace("/Kg", "", regex=False)
# Replace "-" with NaN
maize_market_prices_df["Wholesale"] = maize_market_prices_df["Wholesale"].replace(" - ", np.nan)
# Convert to numeric
maize_market_prices_df["Wholesale"] = pd.to_numeric(maize_market_prices_df["Wholesale"], errors="coerce")
# Fill missing values with mean
mean_wholesale = maize_market_prices_df["Wholesale"].mean()
print(mean_wholesale)

maize_market_prices_df["Wholesale"] = maize_market_prices_df["Wholesale"].fillna(mean_wholesale)

maize_market_prices_df.columns
maize_market_prices_df

54.80328130947849

      Commodity  Wholesale    Retail       County        Date
0     Dry Maize  50.000000  65.00/Kg  Trans-Nzoia  2026-03-03
1     Dry Maize  44.440000  52.17/Kg     Kakamega  2026-03-02
2     Dry Maize  50.000000  65.00/Kg  Trans-Nzoia  2026-03-02
3     Dry Maize  54.803281  65.00/Kg       Kisumu  2026-03-01
4     Dry Maize  57.780000  65.00/Kg       Kisumu  2026-03-01
...         ...        ...       ...          ...         ...
2995  Dry Maize  60.000000  90.00/Kg      Nairobi  2024-07-10
2996  Dry Maize  30.000000  60.00/Kg      Nairobi  2024-07-10
2997  Dry Maize  37.000000  70.00/Kg      Nairobi  2024-07-10
2998  Dry Maize  61.110000  90.00/Kg      Nairobi  2024-07-10
2999  Dry Maize  33.330000  36.96/Kg       Vihiga  2024-07-10

[3000 rows x 5 columns]

In [18]:
import pandas as pd
import numpy as np
import os
import glob

# Folder containing the raw files
input_folder = "datasets/crop_prices/csv"

# Folder where cleaned files will be saved
output_folder = "datasets/crop_prices/cleaned"

os.makedirs(output_folder, exist_ok=True)

# Get all csv files
files = glob.glob(os.path.join(input_folder, "*.csv"))

for file in files:
    
    print(f"Cleaning {file}...")
    
    df = pd.read_csv(file)
    
    # Keep only needed columns
    df = df[["Commodity", "Wholesale", "Retail", "County", "Date"]]
    
    # Remove /Kg
    df["Wholesale"] = df["Wholesale"].astype(str).str.replace("/Kg", "", regex=False)
    df["Retail"] = df["Retail"].astype(str).str.replace("/Kg", "", regex=False)
    
    # Replace '-' with NaN
    df["Wholesale"] = df["Wholesale"].replace("-", np.nan)
    df["Retail"] = df["Retail"].replace("-", np.nan)
    
    # Convert to numeric
    df["Wholesale"] = pd.to_numeric(df["Wholesale"], errors="coerce")
    df["Retail"] = pd.to_numeric(df["Retail"], errors="coerce")
    
    # Fill missing values with mean
    df["Wholesale"] = df["Wholesale"].fillna(df["Wholesale"].mean())
    df["Retail"] = df["Retail"].fillna(df["Retail"].mean())
    
    # Save cleaned file
    filename = os.path.basename(file)
    output_path = os.path.join(output_folder, filename)
    
    df.to_csv(output_path, index=False)

print("✅ All crop price datasets cleaned successfully.")

Cleaning datasets/crop_prices/csv/tomatoes_market_prices.csv...
Cleaning datasets/crop_prices/csv/coffee_market_prices.csv...
Cleaning datasets/crop_prices/csv/kales_market_prices.csv...
Cleaning datasets/crop_prices/csv/rice_market_prices.csv...
Cleaning datasets/crop_prices/csv/tea_market_prices.csv...
Cleaning datasets/crop_prices/csv/wheat_market_prices.csv...
Cleaning datasets/crop_prices/csv/maize_market_prices.csv...
Cleaning datasets/crop_prices/csv/dry_onions_market_prices.csv...
✅ All crop price datasets cleaned successfully.

In [19]:
merged_df

,Date,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,County,Latitude,Longitude,Soil_pH_0_5cm
0,2010-01-01,34.38,23.11,0.45,71.63,mombasa,-4.0435,39.6682,6.266667
1,2010-01-02,34.48,23.29,2.17,72.44,mombasa,-4.0435,39.6682,6.266667
2,2010-01-03,32.05,23.79,1.89,75.17,mombasa,-4.0435,39.6682,6.266667
3,2010-01-04,34.33,23.96,0.39,70.45,mombasa,-4.0435,39.6682,6.266667
4,2010-01-05,35.09,23.48,1.44,70.43,mombasa,-4.0435,39.6682,6.266667
...,...,...,...,...,...,...,...,...,...
257508,2024-12-27,27.77,14.79,0.14,69.84,nairobi,-1.2864,36.8172,6.225000
257509,2024-12-28,27.24,14.91,0.07,68.94,nairobi,-1.2864,36.8172,6.225000
257510,2024-12-29,28.55,13.60,0.01,64.06,nairobi,-1.2864,36.8172,6.225000
257511,2024-12-30,28.04,13.93,0.05,65.32,nairobi,-1.2864,36.8172,6.225000
257512,2024-12-31,28.35,14.07,0.10,67.79,nairobi,-1.2864,36.8172,6.225000

In [20]:
# import pandas as pd

# climate_df = pd.read_csv("datasets/climate_soil.csv")

# convert date
merged_df["Date"] = pd.to_datetime(merged_df["Date"])

# extract year
merged_df["Year"] = merged_df["Date"].dt.year

# create average features
merged_summary = merged_df.groupby(["County","Year"]).agg({
    "T2M_MAX":"mean",
    "T2M_MIN":"mean",
    "PRECTOTCORR":"sum",
    "RH2M":"mean",
    "Soil_pH_0_5cm":"mean"
}).reset_index()

merged_summary

,County,Year,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,Soil_pH_0_5cm
0,baringo,2010,28.408822,16.093479,992.90,63.949096,6.8
1,baringo,2011,28.423178,16.031096,1059.51,62.470795,6.8
2,baringo,2012,27.876284,15.660820,1128.08,64.856393,6.8
3,baringo,2013,28.415288,16.178384,927.05,63.261836,6.8
4,baringo,2014,29.530027,16.487288,641.36,58.669452,6.8
...,...,...,...,...,...,...,...
700,west pokot,2020,25.337678,15.457596,2200.47,76.778743,6.2
701,west pokot,2021,27.688658,15.518904,970.45,65.715699,6.2
702,west pokot,2022,27.584137,15.299726,1161.90,64.964411,6.2
703,west pokot,2023,27.634849,15.577041,1405.77,66.959096,6.2
704,west pokot,2024,26.598005,15.968306,1838.25,72.812077,6.2

In [21]:
import pandas as pd
import glob

files = glob.glob("datasets/crop_prices/cleaned/*.csv")

price_list = []

for file in files:
    df = pd.read_csv(file)
    price_list.append(df)

prices_df = pd.concat(price_list, ignore_index=True)

prices_df

        Commodity   Wholesale      Retail        County        Date
0        Tomatoes   80.000000  100.000000         Kwale  2026-03-03
1        Tomatoes   60.000000   80.000000   Trans-Nzoia  2026-03-03
2        Tomatoes   65.192076   60.000000  Taita-Taveta  2026-03-03
3        Tomatoes   60.000000   99.084886  Taita-Taveta  2026-03-03
4        Tomatoes   60.000000   99.084886  Taita-Taveta  2026-03-03
...           ...         ...         ...           ...         ...
18186  Dry Onions   90.000000  100.000000       Bungoma  2024-06-21
18187  Dry Onions  130.000000  180.000000         Kitui  2024-06-21
18188  Dry Onions  233.330000  200.000000        Kilifi  2024-06-21
18189  Dry Onions  150.000000  200.000000   Trans-Nzoia  2024-06-21
18190  Dry Onions  100.000000  120.000000       Nairobi  2024-06-21

[18191 rows x 5 columns]

In [22]:
prices_df["Date"] = pd.to_datetime(prices_df["Date"])
prices_df["Year"] = prices_df["Date"].dt.year

price_summary = prices_df.groupby(["County","Year","Commodity"]).agg({
    "Wholesale":"mean",
    "Retail":"mean"
}).reset_index()

price_summary

         County  Year          Commodity   Wholesale      Retail
0       Baringo  2022              Wheat   46.800000   69.200000
1       Baringo  2023              Wheat   57.333333   80.833333
2         Bomet  2022              Wheat   78.890000  102.085000
3         Bomet  2024          Dry Maize   34.715000   48.364583
4         Bomet  2024         Dry Onions  214.867925  124.150943
..          ...   ...                ...         ...         ...
403      Vihiga  2025           Tomatoes   64.094901  104.873000
404       Wajir  2024         Dry Onions  130.298235  150.000000
405       Wajir  2024  Kales/Sukuma Wiki   62.870579   76.666667
406       Wajir  2024           Tomatoes   40.000000   70.000000
407  West-Pokot  2023              Wheat  100.000000  170.000000

[408 rows x 5 columns]

In [23]:
# print(merged_summary["County"].unique())
# print(price_summary["County"].unique())
def clean_county(name):
    return (
        name.lower()
        .replace("-", " ")
        .replace("'", "")
        .strip()
    )

merged_summary["County"] = merged_summary["County"].apply(clean_county)
price_summary["County"] = price_summary["County"].apply(clean_county)
print(merged_summary["County"].unique())
print(price_summary["County"].unique())

<StringArray>
[        'baringo',           'bomet',         'bungoma',           'busia',
 'elgeyo marakwet',            'embu',         'garissa',        'homa bay',
          'isiolo',         'kajiado',        'kakamega',         'kericho',
          'kiambu',          'kilifi',       'kirinyaga',           'kisii',
          'kisumu',           'kitui',           'kwale',        'laikipia',
            'lamu',        'machakos',         'makueni',         'mandera',
        'marsabit',            'meru',          'migori',         'mombasa',
         'muranga',         'nairobi',          'nakuru',           'nandi',
           'narok',         'nyamira',       'nyandarua',           'nyeri',
         'samburu',           'siaya',    'taita taveta',      'tana river',
   'tharaka nithi',     'trans nzoia',         'turkana',     'uasin gishu',
          'vihiga',           'wajir',      'west pokot']
Length: 47, dtype: str
<StringArray>
[        'baringo',           'bomet',         'bungoma',           'busia',
 'elgeyo marakwet',            'embu',         'garissa',        'homa bay',
          'isiolo',         'kajiado',        'kakamega',         'kericho',
          'kiambu',          'kilifi',       'kirinyaga',           'kisii',
          'kisumu',           'kitui',           'kwale',        'laikipia',
            'lamu',        'machakos',         'makueni',         'mandera',
            'meru',          'migori',         'mombasa',         'muranga',
         'nairobi',          'nakuru',           'nandi',           'narok',
         'nyamira',       'nyandarua',           'nyeri',         'samburu',
           'siaya',    'taita taveta',      'tana river',   'tharaka nithi',
     'trans nzoia',         'turkana',     'uasin gishu',          'vihiga',
           'wajir',      'west pokot']
Length: 46, dtype: str

In [24]:
# merge climate and price datasets
merged_df = pd.merge(
    merged_summary,
    price_summary,
    on=["County","Year"],
    how="inner"
)

merged_df

,County,Year,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,Soil_pH_0_5cm,Commodity,Wholesale,Retail
0,baringo,2022,29.350466,15.935315,890.25,60.413753,6.800000,Wheat,46.800000,69.200000
1,baringo,2023,29.392356,16.246767,1120.88,62.320082,6.800000,Wheat,57.333333,80.833333
2,bomet,2022,25.896055,12.360027,805.47,66.778849,6.766667,Wheat,78.890000,102.085000
3,bomet,2024,23.605410,12.539098,1754.47,78.862814,6.766667,Dry Maize,34.715000,48.364583
4,bomet,2024,23.605410,12.539098,1754.47,78.862814,6.766667,Dry Onions,214.867925,124.150943
...,...,...,...,...,...,...,...,...,...,...
226,vihiga,2024,25.117732,16.511421,3042.99,76.261885,5.500000,Tomatoes,67.998051,82.182778
227,wajir,2024,35.914426,23.919699,321.84,54.807951,7.600000,Dry Onions,130.298235,150.000000
228,wajir,2024,35.914426,23.919699,321.84,54.807951,7.600000,Kales/Sukuma Wiki,62.870579,76.666667
229,wajir,2024,35.914426,23.919699,321.84,54.807951,7.600000,Tomatoes,40.000000,70.000000
230,west pokot,2023,27.634849,15.577041,1405.77,66.959096,6.200000,Wheat,100.000000,170.000000

In [47]:
merged_df["AvgTemp"] = (merged_df["T2M_MAX"] + merged_df["T2M_MIN"]) / 2
merged_df["Price"] = (merged_df["Wholesale"] + merged_df["Retail"]) / 2
merged_df["Soil_pH"] = merged_df["Soil_pH_0_5cm"]
merged_df["Humidity"] = merged_df["RH2M"]
merged_df["Rainfall"] = merged_df["PRECTOTCORR"]
merged_df["Crop"] = merged_df["Commodity"]
# merged_df
merged_df["Price"] = merged_df["Price"].fillna(
    merged_df.groupby("Crop")["Price"].transform("mean")
)

ml_df = merged_df[[
    "County",
    "Crop",
    "AvgTemp",
    "Rainfall",
    "Humidity",
    "Soil_pH",
    "Price",
]]
ml_df["Price"].isna().sum()

np.int64(25)

In [49]:
ml_df["Price"] = ml_df["Price"].fillna(ml_df["Price"].mean())
ml_df["Price"].isna().sum()

np.int64(0)

In [51]:
ml_df.to_csv("datasets/final_crop_dataset4.csv", index=False)