In [79]:
import pandas as pd

In [80]:
climate_df = pd.read_csv('datasets/weather/Kenya_All_Counties_Climate_Data_2010_2024.csv')
soil_df = pd.read_csv('datasets/soil/Kenya_Counties_Soil_pH.csv')

In [81]:
# clean county names
climate_df["County"] = climate_df["County"].str.strip().str.lower()
soil_df["County"] = soil_df["County"].str.strip().str.lower()

In [82]:
soil_df

             County  Latitude  Longitude  Soil_pH_0_5cm
0           mombasa   -4.0435    39.6682            NaN
1             kwale   -4.1737    39.4521            5.8
2            kilifi   -3.5106    39.9093            6.3
3        tana river   -1.5011    40.0334            7.4
4              lamu   -2.2697    40.9020            NaN
5      taita taveta   -3.3980    38.5560            6.7
6           garissa   -0.4532    39.6460            NaN
7             wajir    1.7471    40.0573            7.6
8           mandera    3.9373    41.8569            NaN
9          marsabit    2.3284    37.9899            7.0
10           isiolo    0.3556    37.5822            6.5
11             meru    0.0470    37.6498            5.5
12    tharaka-nithi   -0.2965    37.7237            5.9
13             embu   -0.5394    37.4572            5.9
14            kitui   -1.3670    38.0106            6.4
15         machakos   -1.5177    37.2634            6.1
16          makueni   -1.8041    37.6200            6.0
17        nyandarua   -0.1800    36.5220            5.8
18            nyeri   -0.4167    36.9500            6.2
19        kirinyaga   -0.6591    37.3827            5.9
20         murang'a   -0.7167    37.1500            6.0
21           kiambu   -1.1714    36.8356            6.1
22          turkana    3.1167    35.6000            7.9
23       west pokot    1.6210    35.2300            6.2
24          samburu    1.2150    36.9540            7.0
25      trans nzoia    1.0191    35.0023            NaN
26      uasin gishu    0.5143    35.2698            6.1
27  elgeyo-marakwet    0.8025    35.4780            5.9
28            nandi    0.1836    35.1260            5.6
29          baringo    0.4667    35.9667            6.8
30         laikipia    0.3600    36.7819            6.9
31           nakuru   -0.3031    36.0800            NaN
32            narok   -1.0870    35.8640            6.7
33          kajiado   -1.8523    36.7768            6.7
34          kericho   -0.3670    35.2830            NaN
35            bomet   -0.7830    35.3420            NaN
36         kakamega    0.2827    34.7519            NaN
37           vihiga    0.0780    34.7210            5.5
38          bungoma    0.5690    34.5580            NaN
39            busia    0.4600    34.1110            NaN
40            siaya    0.0610    34.2880            5.6
41           kisumu   -0.1022    34.7617            NaN
42         homa bay   -0.5273    34.4571            NaN
43           migori   -1.0634    34.4731            NaN
44            kisii   -0.6833    34.7667            5.4
45          nyamira   -0.5667    34.9333            5.3
46          nairobi   -1.2864    36.8172            NaN

In [83]:
# filling null value for mombasa by using near couties mean
# Define neighbors
mombasa_neighbors = ["kwale", "kilifi", "taita taveta"]

# Calculate average soil pH
mombasa_avg_ph = soil_df[
    soil_df["County"].isin(mombasa_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Mombasa soil pH:", mombasa_avg_ph)

# filling null values for nairobi
nairobi_neighbors = ["kiambu", "machakos", "kajiado", "murang'a"]

nairobi_avg_ph = soil_df[
    soil_df["County"].isin(nairobi_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Nairobi soil pH:", nairobi_avg_ph)

# filling null values for garissa
garissa_neighbors = ["wajir", "marsabit"]

garissa_avg_ph = soil_df[
    soil_df["County"].isin(garissa_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Garissa soil pH:", garissa_avg_ph)

# filling null values for trans nzoia
trans_neighbors = ["turkana", "west pokot", "samburu", "uasin gishu"]

trans_avg_ph = soil_df[
    soil_df["County"].isin(trans_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Trans Nzoia soil pH:", trans_avg_ph)

# filling null values for nakuru
nakuru_neighbors = ["laikipia", "narok", "kajiado"]

nakuru_avg_ph = soil_df[
    soil_df["County"].isin(nakuru_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Nakuru soil pH:", nakuru_avg_ph)

# filling null values for nakuru
kakamega_neighbors = ["vihiga", "siaya", "kisii", "nyamira"]

kakamega_avg_ph = soil_df[
    soil_df["County"].isin(kakamega_neighbors)
]["Soil_pH_0_5cm"].mean()

print("Estimated Kakamega soil pH:", kakamega_avg_ph)

Estimated Mombasa soil pH: 6.266666666666667
Estimated Nairobi soil pH: 6.225
Estimated Garissa soil pH: 7.3
Estimated Trans Nzoia soil pH: 6.800000000000001
Estimated Nakuru soil pH: 6.766666666666667
Estimated Kakamega soil pH: 5.45

In [84]:
# filling the missing values
# Fill Mombasa
soil_df.loc[
    (soil_df["County"] == "mombasa") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = mombasa_avg_ph

# fill for lamu use for momabase bcz they are on the same region
soil_df.loc[
    (soil_df["County"] == "lamu") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = mombasa_avg_ph

# Fill Nairobi
soil_df.loc[
    (soil_df["County"] == "nairobi") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nairobi_avg_ph


# Fill Garissa
soil_df.loc[
    (soil_df["County"] == "garissa") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = garissa_avg_ph

# Fill Mandera use Garissa because they are on the same region
soil_df.loc[
    (soil_df["County"] == "mandera") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = garissa_avg_ph

# Fill Trans Nzoia
soil_df.loc[
    (soil_df["County"] == "trans nzoia") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = trans_avg_ph

# Fill Nakuru
soil_df.loc[
    (soil_df["County"] == "nakuru") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nakuru_avg_ph

# Fill Kericho - use nakuru
soil_df.loc[
    (soil_df["County"] == "kericho") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nakuru_avg_ph

# Fill bomet - use nakuru
soil_df.loc[
    (soil_df["County"] == "bomet") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = nakuru_avg_ph

# Fill kakamega
soil_df.loc[
    (soil_df["County"] == "kakamega") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill bungoma
soil_df.loc[
    (soil_df["County"] == "bungoma") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill busia - use kakamega
soil_df.loc[
    (soil_df["County"] == "busia") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill kisumu - use kakamega
soil_df.loc[
    (soil_df["County"] == "kisumu") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill homa bay - use kakamega
soil_df.loc[
    (soil_df["County"] == "homa bay") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

# Fill migori - use kakamega
soil_df.loc[
    (soil_df["County"] == "migori") &
    (soil_df["Soil_pH_0_5cm"].isnull()),
    "Soil_pH_0_5cm"
] = kakamega_avg_ph

In [85]:
soil_df

             County  Latitude  Longitude  Soil_pH_0_5cm
0           mombasa   -4.0435    39.6682       6.266667
1             kwale   -4.1737    39.4521       5.800000
2            kilifi   -3.5106    39.9093       6.300000
3        tana river   -1.5011    40.0334       7.400000
4              lamu   -2.2697    40.9020       6.266667
5      taita taveta   -3.3980    38.5560       6.700000
6           garissa   -0.4532    39.6460       7.300000
7             wajir    1.7471    40.0573       7.600000
8           mandera    3.9373    41.8569       7.300000
9          marsabit    2.3284    37.9899       7.000000
10           isiolo    0.3556    37.5822       6.500000
11             meru    0.0470    37.6498       5.500000
12    tharaka-nithi   -0.2965    37.7237       5.900000
13             embu   -0.5394    37.4572       5.900000
14            kitui   -1.3670    38.0106       6.400000
15         machakos   -1.5177    37.2634       6.100000
16          makueni   -1.8041    37.6200       6.000000
17        nyandarua   -0.1800    36.5220       5.800000
18            nyeri   -0.4167    36.9500       6.200000
19        kirinyaga   -0.6591    37.3827       5.900000
20         murang'a   -0.7167    37.1500       6.000000
21           kiambu   -1.1714    36.8356       6.100000
22          turkana    3.1167    35.6000       7.900000
23       west pokot    1.6210    35.2300       6.200000
24          samburu    1.2150    36.9540       7.000000
25      trans nzoia    1.0191    35.0023       6.800000
26      uasin gishu    0.5143    35.2698       6.100000
27  elgeyo-marakwet    0.8025    35.4780       5.900000
28            nandi    0.1836    35.1260       5.600000
29          baringo    0.4667    35.9667       6.800000
30         laikipia    0.3600    36.7819       6.900000
31           nakuru   -0.3031    36.0800       6.766667
32            narok   -1.0870    35.8640       6.700000
33          kajiado   -1.8523    36.7768       6.700000
34          kericho   -0.3670    35.2830       6.766667
35            bomet   -0.7830    35.3420       6.766667
36         kakamega    0.2827    34.7519       5.450000
37           vihiga    0.0780    34.7210       5.500000
38          bungoma    0.5690    34.5580       5.450000
39            busia    0.4600    34.1110       5.450000
40            siaya    0.0610    34.2880       5.600000
41           kisumu   -0.1022    34.7617       5.450000
42         homa bay   -0.5273    34.4571       5.450000
43           migori   -1.0634    34.4731       5.450000
44            kisii   -0.6833    34.7667       5.400000
45          nyamira   -0.5667    34.9333       5.300000
46          nairobi   -1.2864    36.8172       6.225000

In [86]:
climate_df.head()

         Date  T2M_MAX  T2M_MIN  PRECTOTCORR   RH2M   County
0  2010-01-01    34.38    23.11         0.45  71.63  mombasa
1  2010-01-02    34.48    23.29         2.17  72.44  mombasa
2  2010-01-03    32.05    23.79         1.89  75.17  mombasa
3  2010-01-04    34.33    23.96         0.39  70.45  mombasa
4  2010-01-05    35.09    23.48         1.44  70.43  mombasa

In [87]:
# merge datasets
merged_df = pd.merge(
    climate_df,
    soil_df,
    on="County",
    how="left"
)

In [88]:
merged_df

,Date,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,County,Latitude,Longitude,Soil_pH_0_5cm
0,2010-01-01,34.38,23.11,0.45,71.63,mombasa,-4.0435,39.6682,6.266667
1,2010-01-02,34.48,23.29,2.17,72.44,mombasa,-4.0435,39.6682,6.266667
2,2010-01-03,32.05,23.79,1.89,75.17,mombasa,-4.0435,39.6682,6.266667
3,2010-01-04,34.33,23.96,0.39,70.45,mombasa,-4.0435,39.6682,6.266667
4,2010-01-05,35.09,23.48,1.44,70.43,mombasa,-4.0435,39.6682,6.266667
...,...,...,...,...,...,...,...,...,...
257508,2024-12-27,27.77,14.79,0.14,69.84,nairobi,-1.2864,36.8172,6.225000
257509,2024-12-28,27.24,14.91,0.07,68.94,nairobi,-1.2864,36.8172,6.225000
257510,2024-12-29,28.55,13.60,0.01,64.06,nairobi,-1.2864,36.8172,6.225000
257511,2024-12-30,28.04,13.93,0.05,65.32,nairobi,-1.2864,36.8172,6.225000
257512,2024-12-31,28.35,14.07,0.10,67.79,nairobi,-1.2864,36.8172,6.225000

In [19]:
merged_df.describe()

,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,Latitude,Longitude,Soil_pH_0_5cm
count,257513.000000,257513.000000,257513.000000,257513.000000,257513.000000,257513.000000,175328.00000
mean,27.828646,16.917751,3.432169,69.586028,-0.371811,36.800251,62.71875
std,4.289686,4.146640,6.795233,11.984808,1.593042,1.939822,6.39452
min,15.020000,3.710000,0.000000,15.470000,-4.173700,34.111000,53.00000
25%,24.710000,14.030000,0.160000,62.080000,-1.171400,35.126000,58.75000
50%,27.470000,16.090000,1.010000,71.660000,-0.367000,36.781900,61.00000
75%,30.520000,19.480000,3.740000,78.640000,0.460000,37.723700,67.00000
max,41.890000,30.670000,408.400000,94.950000,3.937300,41.856900,79.00000

In [89]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 257513 entries, 0 to 257512
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           257513 non-null  str
 1   T2M_MAX        257513 non-null  float64
 2   T2M_MIN        257513 non-null  float64
 3   PRECTOTCORR    257513 non-null  float64
 4   RH2M           257513 non-null  float64
 5   County         257513 non-null  str
 6   Latitude       257513 non-null  float64
 7   Longitude      257513 non-null  float64
 8   Soil_pH_0_5cm  257513 non-null  float64
dtypes: float64(7), str(2)
memory usage: 17.7 MB

In [90]:
merged_df

,Date,T2M_MAX,T2M_MIN,PRECTOTCORR,RH2M,County,Latitude,Longitude,Soil_pH_0_5cm
0,2010-01-01,34.38,23.11,0.45,71.63,mombasa,-4.0435,39.6682,6.266667
1,2010-01-02,34.48,23.29,2.17,72.44,mombasa,-4.0435,39.6682,6.266667
2,2010-01-03,32.05,23.79,1.89,75.17,mombasa,-4.0435,39.6682,6.266667
3,2010-01-04,34.33,23.96,0.39,70.45,mombasa,-4.0435,39.6682,6.266667
4,2010-01-05,35.09,23.48,1.44,70.43,mombasa,-4.0435,39.6682,6.266667
...,...,...,...,...,...,...,...,...,...
257508,2024-12-27,27.77,14.79,0.14,69.84,nairobi,-1.2864,36.8172,6.225000
257509,2024-12-28,27.24,14.91,0.07,68.94,nairobi,-1.2864,36.8172,6.225000
257510,2024-12-29,28.55,13.60,0.01,64.06,nairobi,-1.2864,36.8172,6.225000
257511,2024-12-30,28.04,13.93,0.05,65.32,nairobi,-1.2864,36.8172,6.225000
257512,2024-12-31,28.35,14.07,0.10,67.79,nairobi,-1.2864,36.8172,6.225000

In [91]:
# print null soil PH
null_soil = merged_df[merged_df["Soil_pH_0_5cm"].isnull()]
print(null_soil)

Empty DataFrame
Columns: [Date, T2M_MAX, T2M_MIN, PRECTOTCORR, RH2M, County, Latitude, Longitude, Soil_pH_0_5cm]
Index: []

In [93]:
# crop requirements dataset
crop_requirements_df = pd.read_csv('datasets/crop_requirements/crop_requirements.csv')
crop_requirements_df

                  Crop  Min_Temp  Max_Temp  Min_Rain  Max_Rain  Min_pH  Max_pH
0                Maize        18        30       500       800     5.5     7.5
1                Beans        16        28       400       700     6.0     7.5
2                 Rice        20        35      1000      2000     5.0     6.5
3                Wheat        10        25       500      1200     6.0     7.5
4              Sorghum        20        35       300       800     5.0     7.5
5         Irish Potato        15        22       600      1200     5.0     6.5
6               Tomato        18        30       600      1200     5.5     7.5
7                Onion        13        24       500      1000     6.0     7.5
8   Kale (Sukuma Wiki)        16        28       500      1000     5.5     7.5
9               Coffee        15        24      1200      2000     6.0     6.5
10                 Tea        10        20      1200      2500     4.5     5.5